In [4]:
from dotenv import load_dotenv; 
load_dotenv()
import os
from moexalgo import session, Market, Ticker
import datetime as dt
from tickers import TICKERS
import pandas as pd

def getFormattedDate(timestamp : dt.datetime):
    days = str(timestamp.day)
    if (len(days) < 2):
        days = '0' + days
    month = str(timestamp.month)
    if (len(month) < 2):
        month = '0' + month
    year = str(timestamp.year)
    return f"{year}-{month}-{days}"

def TickerName(ticker, timestamp1:dt.datetime):
    return f"{ticker}_{getFormattedDate(timestamp1)}.csv"

MOEX_TOKEN = os.getenv("MOEX_TOKEN")

session.TOKEN = MOEX_TOKEN

dataBegin = "2011-01-01"
dataBegin = "2025-01-01"
dataEnd = "2025-01-10"


def get_day(ticker : Ticker, dateBegin, dateEnd, filename):
    data_ob = ticker.obstats(start=dateBegin, end=dateEnd)
    data_tr = ticker.tradestats(start=dateBegin, end=dateEnd)
    data_or = ticker.orderstats(start=dateBegin, end=dateEnd)    
    return (data_tr, data_or, data_ob)
    print(data_or.columns, data_ob.columns, data_tr.columns)

    data = pd.merge(data_ob, data_tr, on=("tradedate", "tradetime"), how="inner")
    data = pd.merge(data, data_or, on=("tradedate", "tradetime"), how="inner")
    data.to_csv(filename)

def load_ticker(tickerSymb, dateBegin, dateEnd):
    begin = dt.datetime.strptime(dateBegin, "%Y-%m-%d").date()
    end = dt.datetime.strptime(dateEnd, "%Y-%m-%d").date()
    ticker = Ticker(tickerSymb)

    while (begin <= end): 
        name = f"./{tickerSymb}/{TickerName(tickerSymb, begin)}"
        cur = getFormattedDate(begin)
        print(f"loading {cur}",end=" ")
        begin += dt.timedelta(days=1)
        curp1 = getFormattedDate(begin)

        get_day(ticker, cur, curp1, name)
        print("loaded;")
    
#load_ticker(TICKERS[0], dataBegin, dataEnd)

245

In [5]:
data0 = get_day(Ticker("SBER"), dataBegin, dataEnd, "")

In [6]:
def DataTransform(data_ob, data_tr, data_or):
    data_ob = data_ob.drop(columns=["systime"])
    data_ob.rename(columns={'val_b': 'val_b_obstat', 'val_s': 'val_s_obstat', 'vol_b': 'vol_b_obstat', 'vol_s': 'vol_s_obstat'}, inplace=True)
    
    data_tr = data_tr.drop(columns=["systime"])
    
    data_or = data_or.drop(columns=["systime"])
    data_or.rename(columns={'val_b': 'val_b_order', 'val_s': 'val_s_order', 'vol_b': 'vol_b_order', 'vol_s': 'vol_s_order'}, inplace=True)

    return data_ob, data_tr, data_or

#print(*sorted(list(data0[0].columns)), sep="\n",end="\n\n")
data1 = DataTransform(*data0)
print(*sorted(list(data1[0].columns)), sep="\n",end="\n\n")

disb
pr_change
pr_close
pr_high
pr_low
pr_open
pr_std
pr_vwap
pr_vwap_b
pr_vwap_s
sec_pr_close
sec_pr_high
sec_pr_low
sec_pr_open
ticker
tradedate
trades
trades_b
trades_s
tradetime
val
val_b_obstat
val_s_obstat
vol
vol_b_obstat
vol_s_obstat

In [7]:
data2 = pd.merge(data1[0], data1[1], on=("tradedate", "tradetime", "ticker"), how="inner")
data3 = pd.merge(data2, data1[2], on=("tradedate", "tradetime", "ticker"), how="inner")
print(*sorted(list(data3.columns)), sep="\n",end="\n\n")
data3.to_csv("look.csv", index=False)

cancel_orders
cancel_orders_b
cancel_orders_s
cancel_val
cancel_val_b
cancel_val_s
cancel_vol
cancel_vol_b
cancel_vol_s
cancel_vwap_b
cancel_vwap_s
disb
imbalance_val
imbalance_val_bbo
imbalance_vol
imbalance_vol_bbo
levels_b
levels_s
pr_change
pr_close
pr_high
pr_low
pr_open
pr_std
pr_vwap
pr_vwap_b
pr_vwap_s
put_orders
put_orders_b
put_orders_s
put_val
put_val_b
put_val_s
put_vol
put_vol_b
put_vol_s
put_vwap_b
put_vwap_s
sec_pr_close
sec_pr_high
sec_pr_low
sec_pr_open
spread_1mio
spread_bbo
spread_lv10
ticker
tradedate
trades
trades_b
trades_s
tradetime
val
val_b_obstat
val_b_order
val_s_obstat
val_s_order
vol
vol_b_obstat
vol_b_order
vol_s_obstat
vol_s_order
vwap_b
vwap_b_1mio
vwap_s
vwap_s_1mio

In [8]:
ids = data3["val_b_x"] != data3["val_b_y"]
data3[ids][["val_b_x", "val_b_y"]]

KeyError: 'val_b_x'

In [ ]:
print(data[0].columns, data[1].columns, data[2].columns, sep="\n\n")

Index(['tradedate', 'tradetime', 'ticker', 'pr_open', 'pr_high', 'pr_low',
       'pr_close', 'pr_std', 'vol', 'val', 'trades', 'pr_vwap', 'pr_change',
       'trades_b', 'trades_s', 'val_b', 'val_s', 'vol_b', 'vol_s', 'disb',
       'pr_vwap_b', 'pr_vwap_s', 'systime', 'sec_pr_open', 'sec_pr_high',
       'sec_pr_low', 'sec_pr_close'],
      dtype='str')

Index(['tradedate', 'tradetime', 'ticker', 'put_orders_b', 'put_orders_s',
       'put_val_b', 'put_val_s', 'put_vol_b', 'put_vol_s', 'put_vwap_b',
       'put_vwap_s', 'put_vol', 'put_val', 'put_orders', 'cancel_orders_b',
       'cancel_orders_s', 'cancel_val_b', 'cancel_val_s', 'cancel_vol_b',
       'cancel_vol_s', 'cancel_vwap_b', 'cancel_vwap_s', 'cancel_vol',
       'cancel_val', 'cancel_orders', 'systime'],
      dtype='str')

Index(['tradedate', 'tradetime', 'ticker', 'spread_bbo', 'spread_lv10',
       'spread_1mio', 'levels_b', 'levels_s', 'vol_b', 'vol_s', 'val_b',
       'val_s', 'imbalance_vol_bbo', 'imbalance_val_bbo', 'imbalance_vol',
       'imbalance_val', 'vwap_b', 'vwap_s', 'vwap_b_1mio', 'vwap_s_1mio',
       'systime'],
      dtype='str')

In [ ]:

print(*sorted(list(data2.columns)), sep="\n")
print(len(set(data2.columns)))
a = list(data2.columns)

for i in a:
    if ('_x' in i):
        print(i)

cancel_orders
cancel_orders_b
cancel_orders_s
cancel_val
cancel_val_b
cancel_val_s
cancel_vol
cancel_vol_b
cancel_vol_s
cancel_vwap_b
cancel_vwap_s
disb
pr_change
pr_close
pr_high
pr_low
pr_open
pr_std
pr_vwap
pr_vwap_b
pr_vwap_s
put_orders
put_orders_b
put_orders_s
put_val
put_val_b
put_val_s
put_vol
put_vol_b
put_vol_s
put_vwap_b
put_vwap_s
sec_pr_close
sec_pr_high
sec_pr_low
sec_pr_open
systime_x
systime_y
ticker
tradedate
trades
trades_b
trades_s
tradetime
val
val_b
val_s
vol
vol_b
vol_s
50
systime_x

In [ ]:
print(data2["systime_x"], data2["systime_y"])

0      2025-01-03 10:05:10
1      2025-01-03 10:10:10
2      2025-01-03 10:15:10
3      2025-01-03 10:20:10
4      2025-01-03 10:25:10
              ...
800    2025-01-10 23:30:10
801    2025-01-10 23:35:10
802    2025-01-10 23:40:10
803    2025-01-10 23:45:10
804    2025-01-10 23:50:10
Name: systime_x, Length: 805, dtype: str 0      2025-01-03 10:05:13
1      2025-01-03 10:10:13
2      2025-01-03 10:15:12
3      2025-01-03 10:20:22
4      2025-01-03 10:25:12
              ...
800    2025-01-10 23:30:14
801    2025-01-10 23:35:14
802    2025-01-10 23:40:14
803    2025-01-10 23:45:14
804    2025-01-10 23:50:14
Name: systime_y, Length: 805, dtype: str

In [ ]:
ids = data2["systime_y"] != data2["systime_x"]

print(ids)
print(data2[ids][("systime_y", "systime_x")])

0      True
1      True
2      True
3      True
4      True
       ...
800    True
801    True
802    True
803    True
804    True
Length: 805, dtype: bool
      tradedate tradetime ticker  pr_open  pr_high  pr_low  pr_close  pr_std  \
0    2025-01-03  10:05:00   SBER   279.99   280.41  279.20    279.54  0.0001
1    2025-01-03  10:10:00   SBER   279.54   279.56  278.11    278.40  0.0001
2    2025-01-03  10:15:00   SBER   278.53   279.21  278.14    278.40  0.0001
3    2025-01-03  10:20:00   SBER   278.42   279.01  278.30    278.32  0.0000
4    2025-01-03  10:25:00   SBER   278.32   278.44  277.77    277.80  0.0000
..          ...       ...    ...      ...      ...     ...       ...     ...
800  2025-01-10  23:30:00   SBER   278.86   279.03  278.85    279.03  0.0001
801  2025-01-10  23:35:00   SBER   279.03   279.04  278.75    278.80  0.0001
802  2025-01-10  23:40:00   SBER   278.80   278.96  278.80    278.89  0.0001
803  2025-01-10  23:45:00   SBER   278.89   279.03  278.83    278.96  0.0001
804  2025-01-10  23:50:00   SBER   278.94   278.99  278.47    278.77  0.0001

        vol        val  ...  cancel_val_b  cancel_val_s  cancel_vol_b  \
0    241287  675113092  ...   21434894764   27071918391       7664438
1    228933  638680676  ...   36033349987   41788054262      12931057
2    101954  284080626  ...   44081210119   39096797762      15823471
3     61568  171522940  ...   16225824374   14800182586       5824827
4    117768  327574944  ...    5792588440   12755965881       2084430
..      ...        ...  ...           ...           ...           ...
800   14267   39794558  ...     331046565     422766287        118854
801   12178   33961269  ...     484471458    1805337167        173838
802    4922   13726514  ...     139581360     592420147         50101
803   22296   62192211  ...     370925179     578302701        133170
804   31457   87688837  ...     296391891     351441671        106761

     cancel_vol_s  cancel_vwap_b  cancel_vwap_s  cancel_vol   cancel_val  \
0         9668789         279.67         279.99    17333227  48506813155
1        14981542         278.66         278.93    27912599  77821404249
2        14022901         278.58         278.81    29846372  83178007881
3         5309202         278.56         278.76    11134029  31026006961
4         4584570         277.90         278.24     6669000  18548554321
..            ...            ...            ...         ...          ...
800        151471         278.53         279.11      270325    753812852
801        646858         278.69         279.09      820696   2289808626
802        212294         278.60         279.06      262395    732001507
803        207176         278.54         279.14      340346    949227881
804        125736         277.62         279.51      232497    647833562

     cancel_orders            systime_y
0           104494  2025-01-03 10:05:13
1           159397  2025-01-03 10:10:13
2           154914  2025-01-03 10:15:12
3            63284  2025-01-03 10:20:22
4            34879  2025-01-03 10:25:12
..             ...                  ...
800           1392  2025-01-10 23:30:14
801           2637  2025-01-10 23:35:14
802           1164  2025-01-10 23:40:14
803           1868  2025-01-10 23:45:14
804           1736  2025-01-10 23:50:14

[805 rows x 50 columns]

In [11]:
def DataTransform(data_ob, data_tr, data_or):
    data_ob = data_ob.drop(columns=["systime"])
    data_ob.rename(columns={'val_b': 'val_b_obstat', 'val_s': 'val_s_obstat', 'vol_b': 'vol_b_obstat', 'vol_s': 'vol_s_obstat'}, inplace=True)
    
    data_tr = data_tr.drop(columns=["systime"])
    
    data_or = data_or.drop(columns=["systime"])
    data_or.rename(columns={'val_b': 'val_b_order', 'val_s': 'val_s_order', 'vol_b': 'vol_b_order', 'vol_s': 'vol_s_order'}, inplace=True)

    data = pd.merge(data_ob, data_tr, on=("tradedate", "tradetime", "ticker"), how="inner")
    data = pd.merge(data, data_ob, on=("tradedate", "tradetime", "ticker"), how="inner")

    return data

In [12]:
data1 = DataTransform(*data0)
data1

,tradedate,tradetime,ticker,pr_open_x,pr_high_x,pr_low_x,pr_close_x,pr_std_x,vol_x,val_x,...,val_s_obstat_y,vol_b_obstat_y,vol_s_obstat_y,disb_y,pr_vwap_b_y,pr_vwap_s_y,sec_pr_open_y,sec_pr_high_y,sec_pr_low_y,sec_pr_close_y
0,2025-01-03,10:05:00,SBER,279.99,280.41,279.20,279.54,0.0001,241287,675113092,...,383391941,104248,137039,-0.14,279.83,279.77,1,159,102,300
1,2025-01-03,10:10:00,SBER,279.54,279.56,278.11,278.40,0.0001,228933,638680676,...,420828593,78102,150831,-0.32,278.93,279.01,1,1,232,300
2,2025-01-03,10:15:00,SBER,278.53,279.21,278.14,278.40,0.0001,101954,284080626,...,157516287,45401,56553,-0.11,278.77,278.53,2,139,9,300
3,2025-01-03,10:20:00,SBER,278.42,279.01,278.30,278.32,0.0000,61568,171522940,...,88642118,29745,31823,-0.03,278.64,278.55,1,167,289,300
4,2025-01-03,10:25:00,SBER,278.32,278.44,277.77,277.80,0.0000,117768,327574944,...,250086654,27861,89907,-0.53,278.12,278.16,1,41,274,300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,2025-01-10,23:30:00,SBER,278.86,279.03,278.85,279.03,0.0001,14267,39794558,...,4540885,12639,1628,0.77,278.93,278.92,9,271,10,295
801,2025-01-10,23:35:00,SBER,279.03,279.04,278.75,278.80,0.0001,12178,33961269,...,28791975,1853,10325,-0.70,278.97,278.86,6,10,224,293
802,2025-01-10,23:40:00,SBER,278.80,278.96,278.80,278.89,0.0001,4922,13726514,...,2309117,4094,828,0.66,278.88,278.88,6,15,6,300
803,2025-01-10,23:45:00,SBER,278.89,279.03,278.83,278.96,0.0001,22296,62192211,...,18188284,15774,6522,0.41,278.96,278.88,2,86,99,298
804,2025-01-10,23:50:00,SBER,278.94,278.99,278.47,278.77,0.0001,31457,87688837,...,71091141,5953,25504,-0.62,278.81,278.75,2,30,275,298

In [6]:
from dotenv import load_dotenv; 
load_dotenv()
import os
from moexalgo import session, Market, Ticker
import datetime as dt
from tickers import TICKERS
import pandas as pd
import sys

def GetFormattedDate(timestamp : dt.datetime):
    days = str(timestamp.day)
    if (len(days) < 2):
        days = '0' + days
    month = str(timestamp.month)
    if (len(month) < 2):
        month = '0' + month
    year = str(timestamp.year)
    return f"{year}-{month}-{days}"

def TickerFilename1(ticker, timestamp1:dt.datetime):
    return f"{ticker}_{GetFormattedDate(timestamp1)}.csv"

def TickerFilename2(ticker, timestamp1:dt.datetime, timestamp2:dt.datetime):
    return f"{ticker}_{GetFormattedDate(timestamp1)}_{GetFormattedDate(timestamp2)}.csv"

def TickerFilename2str(ticker, timestamp1:str, timestamp2:str):
    return f"{ticker}_{timestamp1}_{timestamp2}.csv"

def LoadTicker(tickerSymb, dateBegin, dateEnd) -> list[pd.DataFrame]:

    ticker = Ticker(tickerSymb)

    dfs = []

    data = ticker.candles(
        start=dateBegin,
        end="today",
        period=1
    )
    begin = data["begin"].min().split(' ')[0]
    print()


    while (begin <= dateEnd): 
        begin0 = begin
        data = ticker.candles(
            start=begin,
            end="today",
            period=1
        )

        begin = data["begin"].max().split(' ')[0]
        dfs.append(data)

        if not (data is None):
            name = f"./dataset/{tickerSymb}/frac_data/{TickerFilename2str(tickerSymb, begin0, begin)}"
            print("loaded", begin0, begin, name)
            data.to_csv(name, index=False)
            
        else:
            print("empty", begin0, begin)
    return dfs



MOEX_TOKEN = os.getenv("MOEX_TOKEN")
session.TOKEN = MOEX_TOKEN
dataBegin = "2005-01-01"
dataEnd   = "2026-03-20"

def MergeDatasets(ticker_symb, df_list):
    combined_df = pd.concat(df_list, ignore_index=True)
    combined_df = combined_df.drop_duplicates(subset=['begin'], keep='first')
    combined_df['begin'] = pd.to_datetime(combined_df['begin'])
    combined_df['end']   = pd.to_datetime(combined_df['end'])

    combined_df.sort_values('begin', ignore_index=True)
    print(combined_df)
    combined_df.to_csv(f"./dataset/{ticker_symb}/{ticker_symb}_BASIC_FULL.csv", index=False)

ticker = "ALRS"
dfs = LoadTicker(ticker, dataBegin, dataEnd)
MergeDatasets(ticker, dfs)

loaded 2012-10-02 2013-03-18 ./dataset/ALRS/frac_data/ALRS_2012-10-02_2013-03-18.csv
loaded 2013-03-18 2013-08-28 ./dataset/ALRS/frac_data/ALRS_2013-03-18_2013-08-28.csv
loaded 2013-08-28 2013-11-12 ./dataset/ALRS/frac_data/ALRS_2013-08-28_2013-11-12.csv
loaded 2013-11-12 2014-01-15 ./dataset/ALRS/frac_data/ALRS_2013-11-12_2014-01-15.csv
loaded 2014-01-15 2014-03-03 ./dataset/ALRS/frac_data/ALRS_2014-01-15_2014-03-03.csv
loaded 2014-03-03 2014-04-21 ./dataset/ALRS/frac_data/ALRS_2014-03-03_2014-04-21.csv
loaded 2014-04-21 2014-06-02 ./dataset/ALRS/frac_data/ALRS_2014-04-21_2014-06-02.csv
loaded 2014-06-02 2014-07-09 ./dataset/ALRS/frac_data/ALRS_2014-06-02_2014-07-09.csv
loaded 2014-07-09 2014-08-20 ./dataset/ALRS/frac_data/ALRS_2014-07-09_2014-08-20.csv
loaded 2014-08-20 2014-09-30 ./dataset/ALRS/frac_data/ALRS_2014-08-20_2014-09-30.csv
loaded 2014-09-30 2014-11-07 ./dataset/ALRS/frac_data/ALRS_2014-09-30_2014-11-07.csv
loaded 2014-11-07 2014-12-15 ./dataset/ALRS/frac_data/ALRS_2014-11-07_2014-12-15.csv
loaded 2014-12-15 2015-01-20 ./dataset/ALRS/frac_data/ALRS_2014-12-15_2015-01-20.csv
loaded 2015-01-20 2015-02-17 ./dataset/ALRS/frac_data/ALRS_2015-01-20_2015-02-17.csv
loaded 2015-02-17 2015-03-20 ./dataset/ALRS/frac_data/ALRS_2015-02-17_2015-03-20.csv
loaded 2015-03-20 2015-04-20 ./dataset/ALRS/frac_data/ALRS_2015-03-20_2015-04-20.csv
loaded 2015-04-20 2015-05-22 ./dataset/ALRS/frac_data/ALRS_2015-04-20_2015-05-22.csv
loaded 2015-05-22 2015-06-23 ./dataset/ALRS/frac_data/ALRS_2015-05-22_2015-06-23.csv
loaded 2015-06-23 2015-07-22 ./dataset/ALRS/frac_data/ALRS_2015-06-23_2015-07-22.csv
loaded 2015-07-22 2015-08-21 ./dataset/ALRS/frac_data/ALRS_2015-07-22_2015-08-21.csv
loaded 2015-08-21 2015-09-18 ./dataset/ALRS/frac_data/ALRS_2015-08-21_2015-09-18.csv
loaded 2015-09-18 2015-10-16 ./dataset/ALRS/frac_data/ALRS_2015-09-18_2015-10-16.csv
loaded 2015-10-16 2015-11-16 ./dataset/ALRS/frac_data/ALRS_2015-10-16_2015-11-16.csv
loaded 2015-11-16 2015-12-14 ./dataset/ALRS/frac_data/ALRS_2015-11-16_2015-12-14.csv
loaded 2015-12-14 2016-01-18 ./dataset/ALRS/frac_data/ALRS_2015-12-14_2016-01-18.csv
loaded 2016-01-18 2016-02-12 ./dataset/ALRS/frac_data/ALRS_2016-01-18_2016-02-12.csv
loaded 2016-02-12 2016-03-14 ./dataset/ALRS/frac_data/ALRS_2016-02-12_2016-03-14.csv
loaded 2016-03-14 2016-04-11 ./dataset/ALRS/frac_data/ALRS_2016-03-14_2016-04-11.csv
loaded 2016-04-11 2016-05-12 ./dataset/ALRS/frac_data/ALRS_2016-04-11_2016-05-12.csv
loaded 2016-05-12 2016-06-09 ./dataset/ALRS/frac_data/ALRS_2016-05-12_2016-06-09.csv
loaded 2016-06-09 2016-07-08 ./dataset/ALRS/frac_data/ALRS_2016-06-09_2016-07-08.csv
loaded 2016-07-08 2016-08-04 ./dataset/ALRS/frac_data/ALRS_2016-07-08_2016-08-04.csv
loaded 2016-08-04 2016-09-02 ./dataset/ALRS/frac_data/ALRS_2016-08-04_2016-09-02.csv
loaded 2016-09-02 2016-09-30 ./dataset/ALRS/frac_data/ALRS_2016-09-02_2016-09-30.csv
loaded 2016-09-30 2016-10-27 ./dataset/ALRS/frac_data/ALRS_2016-09-30_2016-10-27.csv
loaded 2016-10-27 2016-11-24 ./dataset/ALRS/frac_data/ALRS_2016-10-27_2016-11-24.csv
loaded 2016-11-24 2016-12-21 ./dataset/ALRS/frac_data/ALRS_2016-11-24_2016-12-21.csv
loaded 2016-12-21 2017-01-19 ./dataset/ALRS/frac_data/ALRS_2016-12-21_2017-01-19.csv
loaded 2017-01-19 2017-02-15 ./dataset/ALRS/frac_data/ALRS_2017-01-19_2017-02-15.csv
loaded 2017-02-15 2017-03-16 ./dataset/ALRS/frac_data/ALRS_2017-02-15_2017-03-16.csv
loaded 2017-03-16 2017-04-12 ./dataset/ALRS/frac_data/ALRS_2017-03-16_2017-04-12.csv
loaded 2017-04-12 2017-05-12 ./dataset/ALRS/frac_data/ALRS_2017-04-12_2017-05-12.csv
loaded 2017-05-12 2017-06-08 ./dataset/ALRS/frac_data/ALRS_2017-05-12_2017-06-08.csv
loaded 2017-06-08 2017-07-06 ./dataset/ALRS/frac_data/ALRS_2017-06-08_2017-07-06.csv
loaded 2017-07-06 2017-08-02 ./dataset/ALRS/frac_data/ALRS_2017-07-06_2017-08-02.csv
loaded 2017-08-02 2017-08-29 ./dataset/ALRS/frac_data/ALRS_2017-08-02_2017-08-29.csv
loaded 2017-08-29 2017-09-25 ./dataset/ALRS/frac_data/ALRS_2017-08-29_2017-09-25.csv
loaded 2017-09-25 2017-10-20 ./dataset/ALRS/frac_data/ALRS_2017-09-25_2017-10-20.csv
loaded 2017-10-20 2017-11-17 ./dataset/ALRS/frac_data/ALRS_2017-10-20_2017-11-17.csv
loaded 2017-11-17 2017-12-14 ./dataset/ALRS/frac_data/ALRS_2017-11-17_2017-12-14.csv
loaded 2017-12-14 2018-01-16 ./dataset/ALRS/frac_data/ALRS_2017-12-14_2018-01-16.csv
loaded 2018-01-16 2018-02-12 ./dataset/ALRS/frac_data/ALRS_2018-01-16_2018-02-12.csv
loaded 2018-02-12 2018-03-13 ./dataset/ALRS/frac_data/ALRS_2018-02-12_2018-03-13.csv
loaded 2018-03-13 2018-04-10 ./dataset/ALRS/frac_data/ALRS_2018-03-13_2018-04-10.csv
loaded 2018-04-10 2018-05-10 ./dataset/ALRS/frac_data/ALRS_2018-04-10_2018-05-10.csv
loaded 2018-05-10 2018-06-07 ./dataset/ALRS/frac_data/ALRS_2018-05-10_2018-06-07.csv
loaded 2018-06-07 2018-07-05 ./dataset/ALRS/frac_data/ALRS_2018-06-07_2018-07-05.csv
loaded 2018-07-05 2018-08-02 ./dataset/ALRS/frac_data/ALRS_2018-07-05_2018-08-02.csv
loaded 2018-08-02 2018-08-30 ./dataset/ALRS/frac_data/ALRS_2018-08-02_2018-08-30.csv
loaded 2018-08-30 2018-09-27 ./dataset/ALRS/frac_data/ALRS_2018-08-30_2018-09-27.csv
loaded 2018-09-27 2018-10-24 ./dataset/ALRS/frac_data/ALRS_2018-09-27_2018-10-24.csv
loaded 2018-10-24 2018-11-21 ./dataset/ALRS/frac_data/ALRS_2018-10-24_2018-11-21.csv
loaded 2018-11-21 2018-12-18 ./dataset/ALRS/frac_data/ALRS_2018-11-21_2018-12-18.csv
loaded 2018-12-18 2019-01-17 ./dataset/ALRS/frac_data/ALRS_2018-12-18_2019-01-17.csv
loaded 2019-01-17 2019-02-13 ./dataset/ALRS/frac_data/ALRS_2019-01-17_2019-02-13.csv
loaded 2019-02-13 2019-03-13 ./dataset/ALRS/frac_data/ALRS_2019-02-13_2019-03-13.csv
loaded 2019-03-13 2019-04-09 ./dataset/ALRS/frac_data/ALRS_2019-03-13_2019-04-09.csv
loaded 2019-04-09 2019-05-07 ./dataset/ALRS/frac_data/ALRS_2019-04-09_2019-05-07.csv
loaded 2019-05-07 2019-06-04 ./dataset/ALRS/frac_data/ALRS_2019-05-07_2019-06-04.csv
loaded 2019-06-04 2019-07-02 ./dataset/ALRS/frac_data/ALRS_2019-06-04_2019-07-02.csv
loaded 2019-07-02 2019-07-29 ./dataset/ALRS/frac_data/ALRS_2019-07-02_2019-07-29.csv
loaded 2019-07-29 2019-08-23 ./dataset/ALRS/frac_data/ALRS_2019-07-29_2019-08-23.csv
loaded 2019-08-23 2019-09-19 ./dataset/ALRS/frac_data/ALRS_2019-08-23_2019-09-19.csv
loaded 2019-09-19 2019-10-16 ./dataset/ALRS/frac_data/ALRS_2019-09-19_2019-10-16.csv
loaded 2019-10-16 2019-11-13 ./dataset/ALRS/frac_data/ALRS_2019-10-16_2019-11-13.csv
loaded 2019-11-13 2019-12-10 ./dataset/ALRS/frac_data/ALRS_2019-11-13_2019-12-10.csv
loaded 2019-12-10 2020-01-10 ./dataset/ALRS/frac_data/ALRS_2019-12-10_2020-01-10.csv
loaded 2020-01-10 2020-02-06 ./dataset/ALRS/frac_data/ALRS_2020-01-10_2020-02-06.csv
loaded 2020-02-06 2020-03-05 ./dataset/ALRS/frac_data/ALRS_2020-02-06_2020-03-05.csv
loaded 2020-03-05 2020-04-02 ./dataset/ALRS/frac_data/ALRS_2020-03-05_2020-04-02.csv
loaded 2020-04-02 2020-04-29 ./dataset/ALRS/frac_data/ALRS_2020-04-02_2020-04-29.csv
loaded 2020-04-29 2020-05-28 ./dataset/ALRS/frac_data/ALRS_2020-04-29_2020-05-28.csv
loaded 2020-05-28 2020-06-23 ./dataset/ALRS/frac_data/ALRS_2020-05-28_2020-06-23.csv
loaded 2020-06-23 2020-07-13 ./dataset/ALRS/frac_data/ALRS_2020-06-23_2020-07-13.csv
loaded 2020-07-13 2020-07-29 ./dataset/ALRS/frac_data/ALRS_2020-07-13_2020-07-29.csv
loaded 2020-07-29 2020-08-14 ./dataset/ALRS/frac_data/ALRS_2020-07-29_2020-08-14.csv
loaded 2020-08-14 2020-09-01 ./dataset/ALRS/frac_data/ALRS_2020-08-14_2020-09-01.csv
loaded 2020-09-01 2020-09-17 ./dataset/ALRS/frac_data/ALRS_2020-09-01_2020-09-17.csv
loaded 2020-09-17 2020-10-05 ./dataset/ALRS/frac_data/ALRS_2020-09-17_2020-10-05.csv
loaded 2020-10-05 2020-10-21 ./dataset/ALRS/frac_data/ALRS_2020-10-05_2020-10-21.csv
loaded 2020-10-21 2020-11-09 ./dataset/ALRS/frac_data/ALRS_2020-10-21_2020-11-09.csv
loaded 2020-11-09 2020-11-25 ./dataset/ALRS/frac_data/ALRS_2020-11-09_2020-11-25.csv
loaded 2020-11-25 2020-12-11 ./dataset/ALRS/frac_data/ALRS_2020-11-25_2020-12-11.csv
loaded 2020-12-11 2020-12-29 ./dataset/ALRS/frac_data/ALRS_2020-12-11_2020-12-29.csv
loaded 2020-12-29 2021-01-19 ./dataset/ALRS/frac_data/ALRS_2020-12-29_2021-01-19.csv
loaded 2021-01-19 2021-02-04 ./dataset/ALRS/frac_data/ALRS_2021-01-19_2021-02-04.csv
loaded 2021-02-04 2021-02-20 ./dataset/ALRS/frac_data/ALRS_2021-02-04_2021-02-20.csv
loaded 2021-02-20 2021-03-11 ./dataset/ALRS/frac_data/ALRS_2021-02-20_2021-03-11.csv
loaded 2021-03-11 2021-03-29 ./dataset/ALRS/frac_data/ALRS_2021-03-11_2021-03-29.csv
loaded 2021-03-29 2021-04-14 ./dataset/ALRS/frac_data/ALRS_2021-03-29_2021-04-14.csv
loaded 2021-04-14 2021-04-30 ./dataset/ALRS/frac_data/ALRS_2021-04-14_2021-04-30.csv
loaded 2021-04-30 2021-05-19 ./dataset/ALRS/frac_data/ALRS_2021-04-30_2021-05-19.csv
loaded 2021-05-19 2021-06-04 ./dataset/ALRS/frac_data/ALRS_2021-05-19_2021-06-04.csv
loaded 2021-06-04 2021-06-22 ./dataset/ALRS/frac_data/ALRS_2021-06-04_2021-06-22.csv
loaded 2021-06-22 2021-07-08 ./dataset/ALRS/frac_data/ALRS_2021-06-22_2021-07-08.csv
loaded 2021-07-08 2021-07-26 ./dataset/ALRS/frac_data/ALRS_2021-07-08_2021-07-26.csv
loaded 2021-07-26 2021-08-11 ./dataset/ALRS/frac_data/ALRS_2021-07-26_2021-08-11.csv
loaded 2021-08-11 2021-08-27 ./dataset/ALRS/frac_data/ALRS_2021-08-11_2021-08-27.csv
loaded 2021-08-27 2021-09-14 ./dataset/ALRS/frac_data/ALRS_2021-08-27_2021-09-14.csv
loaded 2021-09-14 2021-09-30 ./dataset/ALRS/frac_data/ALRS_2021-09-14_2021-09-30.csv
loaded 2021-09-30 2021-10-18 ./dataset/ALRS/frac_data/ALRS_2021-09-30_2021-10-18.csv
loaded 2021-10-18 2021-11-03 ./dataset/ALRS/frac_data/ALRS_2021-10-18_2021-11-03.csv
loaded 2021-11-03 2021-11-22 ./dataset/ALRS/frac_data/ALRS_2021-11-03_2021-11-22.csv
loaded 2021-11-22 2021-12-07 ./dataset/ALRS/frac_data/ALRS_2021-11-22_2021-12-07.csv
loaded 2021-12-07 2021-12-21 ./dataset/ALRS/frac_data/ALRS_2021-12-07_2021-12-21.csv
loaded 2021-12-21 2022-01-05 ./dataset/ALRS/frac_data/ALRS_2021-12-21_2022-01-05.csv
loaded 2022-01-05 2022-01-20 ./dataset/ALRS/frac_data/ALRS_2022-01-05_2022-01-20.csv
loaded 2022-01-20 2022-02-03 ./dataset/ALRS/frac_data/ALRS_2022-01-20_2022-02-03.csv
loaded 2022-02-03 2022-02-17 ./dataset/ALRS/frac_data/ALRS_2022-02-03_2022-02-17.csv
loaded 2022-02-17 2022-04-08 ./dataset/ALRS/frac_data/ALRS_2022-02-17_2022-04-08.csv
loaded 2022-04-08 2022-05-11 ./dataset/ALRS/frac_data/ALRS_2022-04-08_2022-05-11.csv
loaded 2022-05-11 2022-06-07 ./dataset/ALRS/frac_data/ALRS_2022-05-11_2022-06-07.csv
loaded 2022-06-07 2022-07-05 ./dataset/ALRS/frac_data/ALRS_2022-06-07_2022-07-05.csv
loaded 2022-07-05 2022-08-01 ./dataset/ALRS/frac_data/ALRS_2022-07-05_2022-08-01.csv
loaded 2022-08-01 2022-08-26 ./dataset/ALRS/frac_data/ALRS_2022-08-01_2022-08-26.csv
loaded 2022-08-26 2022-09-19 ./dataset/ALRS/frac_data/ALRS_2022-08-26_2022-09-19.csv
loaded 2022-09-19 2022-10-05 ./dataset/ALRS/frac_data/ALRS_2022-09-19_2022-10-05.csv
loaded 2022-10-05 2022-10-21 ./dataset/ALRS/frac_data/ALRS_2022-10-05_2022-10-21.csv
loaded 2022-10-21 2022-11-09 ./dataset/ALRS/frac_data/ALRS_2022-10-21_2022-11-09.csv
loaded 2022-11-09 2022-11-25 ./dataset/ALRS/frac_data/ALRS_2022-11-09_2022-11-25.csv
loaded 2022-11-25 2022-12-13 ./dataset/ALRS/frac_data/ALRS_2022-11-25_2022-12-13.csv
loaded 2022-12-13 2022-12-29 ./dataset/ALRS/frac_data/ALRS_2022-12-13_2022-12-29.csv
loaded 2022-12-29 2023-01-17 ./dataset/ALRS/frac_data/ALRS_2022-12-29_2023-01-17.csv
loaded 2023-01-17 2023-02-02 ./dataset/ALRS/frac_data/ALRS_2023-01-17_2023-02-02.csv
loaded 2023-02-02 2023-02-20 ./dataset/ALRS/frac_data/ALRS_2023-02-02_2023-02-20.csv
loaded 2023-02-20 2023-03-10 ./dataset/ALRS/frac_data/ALRS_2023-02-20_2023-03-10.csv
loaded 2023-03-10 2023-03-28 ./dataset/ALRS/frac_data/ALRS_2023-03-10_2023-03-28.csv
loaded 2023-03-28 2023-04-13 ./dataset/ALRS/frac_data/ALRS_2023-03-28_2023-04-13.csv
loaded 2023-04-13 2023-05-02 ./dataset/ALRS/frac_data/ALRS_2023-04-13_2023-05-02.csv
loaded 2023-05-02 2023-05-19 ./dataset/ALRS/frac_data/ALRS_2023-05-02_2023-05-19.csv
loaded 2023-05-19 2023-06-06 ./dataset/ALRS/frac_data/ALRS_2023-05-19_2023-06-06.csv
loaded 2023-06-06 2023-06-23 ./dataset/ALRS/frac_data/ALRS_2023-06-06_2023-06-23.csv
loaded 2023-06-23 2023-07-11 ./dataset/ALRS/frac_data/ALRS_2023-06-23_2023-07-11.csv
loaded 2023-07-11 2023-07-27 ./dataset/ALRS/frac_data/ALRS_2023-07-11_2023-07-27.csv
loaded 2023-07-27 2023-08-14 ./dataset/ALRS/frac_data/ALRS_2023-07-27_2023-08-14.csv
loaded 2023-08-14 2023-08-30 ./dataset/ALRS/frac_data/ALRS_2023-08-14_2023-08-30.csv
loaded 2023-08-30 2023-09-15 ./dataset/ALRS/frac_data/ALRS_2023-08-30_2023-09-15.csv
loaded 2023-09-15 2023-10-03 ./dataset/ALRS/frac_data/ALRS_2023-09-15_2023-10-03.csv
loaded 2023-10-03 2023-10-19 ./dataset/ALRS/frac_data/ALRS_2023-10-03_2023-10-19.csv
loaded 2023-10-19 2023-11-06 ./dataset/ALRS/frac_data/ALRS_2023-10-19_2023-11-06.csv
loaded 2023-11-06 2023-11-22 ./dataset/ALRS/frac_data/ALRS_2023-11-06_2023-11-22.csv
loaded 2023-11-22 2023-12-08 ./dataset/ALRS/frac_data/ALRS_2023-11-22_2023-12-08.csv
loaded 2023-12-08 2023-12-26 ./dataset/ALRS/frac_data/ALRS_2023-12-08_2023-12-26.csv
loaded 2023-12-26 2024-01-15 ./dataset/ALRS/frac_data/ALRS_2023-12-26_2024-01-15.csv
loaded 2024-01-15 2024-01-31 ./dataset/ALRS/frac_data/ALRS_2024-01-15_2024-01-31.csv
loaded 2024-01-31 2024-02-16 ./dataset/ALRS/frac_data/ALRS_2024-01-31_2024-02-16.csv
loaded 2024-02-16 2024-03-06 ./dataset/ALRS/frac_data/ALRS_2024-02-16_2024-03-06.csv
loaded 2024-03-06 2024-03-25 ./dataset/ALRS/frac_data/ALRS_2024-03-06_2024-03-25.csv
loaded 2024-03-25 2024-04-10 ./dataset/ALRS/frac_data/ALRS_2024-03-25_2024-04-10.csv
loaded 2024-04-10 2024-04-26 ./dataset/ALRS/frac_data/ALRS_2024-04-10_2024-04-26.csv
loaded 2024-04-26 2024-05-15 ./dataset/ALRS/frac_data/ALRS_2024-04-26_2024-05-15.csv
loaded 2024-05-15 2024-05-31 ./dataset/ALRS/frac_data/ALRS_2024-05-15_2024-05-31.csv
loaded 2024-05-31 2024-06-19 ./dataset/ALRS/frac_data/ALRS_2024-05-31_2024-06-19.csv
loaded 2024-06-19 2024-07-05 ./dataset/ALRS/frac_data/ALRS_2024-06-19_2024-07-05.csv
loaded 2024-07-05 2024-07-23 ./dataset/ALRS/frac_data/ALRS_2024-07-05_2024-07-23.csv
loaded 2024-07-23 2024-08-08 ./dataset/ALRS/frac_data/ALRS_2024-07-23_2024-08-08.csv
loaded 2024-08-08 2024-08-26 ./dataset/ALRS/frac_data/ALRS_2024-08-08_2024-08-26.csv
loaded 2024-08-26 2024-09-11 ./dataset/ALRS/frac_data/ALRS_2024-08-26_2024-09-11.csv
loaded 2024-09-11 2024-09-27 ./dataset/ALRS/frac_data/ALRS_2024-09-11_2024-09-27.csv
loaded 2024-09-27 2024-10-15 ./dataset/ALRS/frac_data/ALRS_2024-09-27_2024-10-15.csv
loaded 2024-10-15 2024-10-31 ./dataset/ALRS/frac_data/ALRS_2024-10-15_2024-10-31.csv
loaded 2024-10-31 2024-11-18 ./dataset/ALRS/frac_data/ALRS_2024-10-31_2024-11-18.csv
loaded 2024-11-18 2024-12-04 ./dataset/ALRS/frac_data/ALRS_2024-11-18_2024-12-04.csv
loaded 2024-12-04 2024-12-20 ./dataset/ALRS/frac_data/ALRS_2024-12-04_2024-12-20.csv
loaded 2024-12-20 2025-01-10 ./dataset/ALRS/frac_data/ALRS_2024-12-20_2025-01-10.csv
loaded 2025-01-10 2025-01-28 ./dataset/ALRS/frac_data/ALRS_2025-01-10_2025-01-28.csv
loaded 2025-01-28 2025-02-11 ./dataset/ALRS/frac_data/ALRS_2025-01-28_2025-02-11.csv
loaded 2025-02-11 2025-02-25 ./dataset/ALRS/frac_data/ALRS_2025-02-11_2025-02-25.csv
loaded 2025-02-25 2025-03-10 ./dataset/ALRS/frac_data/ALRS_2025-02-25_2025-03-10.csv
loaded 2025-03-10 2025-03-21 ./dataset/ALRS/frac_data/ALRS_2025-03-10_2025-03-21.csv
loaded 2025-03-21 2025-04-03 ./dataset/ALRS/frac_data/ALRS_2025-03-21_2025-04-03.csv
loaded 2025-04-03 2025-04-15 ./dataset/ALRS/frac_data/ALRS_2025-04-03_2025-04-15.csv
loaded 2025-04-15 2025-04-28 ./dataset/ALRS/frac_data/ALRS_2025-04-15_2025-04-28.csv
loaded 2025-04-28 2025-05-12 ./dataset/ALRS/frac_data/ALRS_2025-04-28_2025-05-12.csv
loaded 2025-05-12 2025-05-23 ./dataset/ALRS/frac_data/ALRS_2025-05-12_2025-05-23.csv
loaded 2025-05-23 2025-06-05 ./dataset/ALRS/frac_data/ALRS_2025-05-23_2025-06-05.csv
loaded 2025-06-05 2025-06-18 ./dataset/ALRS/frac_data/ALRS_2025-06-05_2025-06-18.csv
loaded 2025-06-18 2025-07-01 ./dataset/ALRS/frac_data/ALRS_2025-06-18_2025-07-01.csv
loaded 2025-07-01 2025-07-14 ./dataset/ALRS/frac_data/ALRS_2025-07-01_2025-07-14.csv
loaded 2025-07-14 2025-07-25 ./dataset/ALRS/frac_data/ALRS_2025-07-14_2025-07-25.csv
loaded 2025-07-25 2025-08-07 ./dataset/ALRS/frac_data/ALRS_2025-07-25_2025-08-07.csv
loaded 2025-08-07 2025-08-20 ./dataset/ALRS/frac_data/ALRS_2025-08-07_2025-08-20.csv
loaded 2025-08-20 2025-09-02 ./dataset/ALRS/frac_data/ALRS_2025-08-20_2025-09-02.csv
loaded 2025-09-02 2025-09-14 ./dataset/ALRS/frac_data/ALRS_2025-09-02_2025-09-14.csv
loaded 2025-09-14 2025-09-27 ./dataset/ALRS/frac_data/ALRS_2025-09-14_2025-09-27.csv
loaded 2025-09-27 2025-10-09 ./dataset/ALRS/frac_data/ALRS_2025-09-27_2025-10-09.csv
loaded 2025-10-09 2025-10-21 ./dataset/ALRS/frac_data/ALRS_2025-10-09_2025-10-21.csv
loaded 2025-10-21 2025-11-03 ./dataset/ALRS/frac_data/ALRS_2025-10-21_2025-11-03.csv
loaded 2025-11-03 2025-11-17 ./dataset/ALRS/frac_data/ALRS_2025-11-03_2025-11-17.csv
loaded 2025-11-17 2025-11-30 ./dataset/ALRS/frac_data/ALRS_2025-11-17_2025-11-30.csv
loaded 2025-11-30 2025-12-13 ./dataset/ALRS/frac_data/ALRS_2025-11-30_2025-12-13.csv
loaded 2025-12-13 2025-12-25 ./dataset/ALRS/frac_data/ALRS_2025-12-13_2025-12-25.csv
loaded 2025-12-25 2026-01-13 ./dataset/ALRS/frac_data/ALRS_2025-12-25_2026-01-13.csv
loaded 2026-01-13 2026-01-25 ./dataset/ALRS/frac_data/ALRS_2026-01-13_2026-01-25.csv
loaded 2026-01-25 2026-02-05 ./dataset/ALRS/frac_data/ALRS_2026-01-25_2026-02-05.csv
loaded 2026-02-05 2026-02-18 ./dataset/ALRS/frac_data/ALRS_2026-02-05_2026-02-18.csv
loaded 2026-02-18 2026-03-03 ./dataset/ALRS/frac_data/ALRS_2026-02-18_2026-03-03.csv
loaded 2026-03-03 2026-03-16 ./dataset/ALRS/frac_data/ALRS_2026-03-03_2026-03-16.csv
loaded 2026-03-16 2026-03-24 ./dataset/ALRS/frac_data/ALRS_2026-03-16_2026-03-24.csv
           open  close    high     low     value  volume               begin  \
0        24.349  24.35  24.350  24.349   12174.8     500 2012-10-02 10:03:00
1        24.350  24.35  24.350  24.350    4870.0     200 2012-10-02 10:06:00
2        24.250  24.25  24.250  24.250    2425.0     100 2012-10-02 10:07:00
3        24.300  24.30  24.325  24.300   34030.0    1400 2012-10-02 10:10:00
4        24.250  24.20  24.250  24.200  653422.1   27000 2012-10-02 10:12:00
...         ...    ...     ...     ...       ...     ...                 ...
2086616  37.080  37.07  37.090  37.070  376351.0   10150 2026-03-24 18:28:00
2086617  37.070  37.07  37.080  37.070   84521.3    2280 2026-03-24 18:29:00
2086618  37.080  37.08  37.090  37.070   84913.1    2290 2026-03-24 18:30:00
2086619  37.080  37.07  37.080  37.070   22984.3     620 2026-03-24 18:31:00
2086620  37.080  37.08  37.090  37.080  409462.1   11040 2026-03-24 18:32:00

                        end
0       2012-10-02 10:03:59
1       2012-10-02 10:06:59
2       2012-10-02 10:07:59
3       2012-10-02 10:10:59
4       2012-10-02 10:12:59
...                     ...
2086616 2026-03-24 18:28:59
2086617 2026-03-24 18:29:59
2086618 2026-03-24 18:30:59
2086619 2026-03-24 18:31:59
2086620 2026-03-24 18:32:53

[2030986 rows x 8 columns]

In [ ]:
def MergeDatasets(ticker_symb, df_list):
    combined_df = pd.concat(df_list, ignore_index=True)
    combined_df = combined_df.drop_duplicates(subset=['begin'], keep='first')
    combined_df['begin'] = pd.to_datetime(combined_df['begin'])
    combined_df['end']   = pd.to_datetime(combined_df['end'])

    combined_df.sort_values('begin', ignore_index=True)
    print(combined_df)
    combined_df.to_csv(f"./dataset/{ticker_symb}/{ticker_symb}_BASIC_FULL.csv", index=False)
MergeDatasets(ticker, dfs)

           open   close    high     low         value   volume  \
0         79.90   79.55   79.98   79.39  1.712688e+08  2151550
1         79.55   79.77   79.78   79.52  1.466276e+08  1841010
2         79.77   79.80   79.87   79.70  4.694636e+07   588320
3         79.80   79.82   79.94   79.78  7.083135e+07   887260
4         79.82   79.88   79.90   79.80  1.481361e+07   185520
...         ...     ...     ...     ...           ...      ...
2412698  317.44  317.35  317.46  317.32  4.394693e+06    13845
2412699  317.32  317.44  317.45  317.31  6.969798e+06    21958
2412700  317.44  317.42  317.44  317.35  1.087633e+06     3427
2412701  317.43  317.47  317.53  317.42  4.146732e+06    13061
2412702  317.47  317.44  317.48  317.41  3.574413e+06    11260

                      begin                 end
0       2011-12-15 10:00:00 2011-12-15 10:00:59
1       2011-12-15 10:01:00 2011-12-15 10:01:59
2       2011-12-15 10:02:00 2011-12-15 10:02:59
3       2011-12-15 10:03:00 2011-12-15 10:03:59
4       2011-12-15 10:04:00 2011-12-15 10:04:59
...                     ...                 ...
2412698 2026-03-23 18:45:00 2026-03-23 18:45:59
2412699 2026-03-23 18:46:00 2026-03-23 18:46:59
2412700 2026-03-23 18:47:00 2026-03-23 18:47:59
2412701 2026-03-23 18:48:00 2026-03-23 18:48:59
2412702 2026-03-23 18:49:00 2026-03-23 18:49:59

[2362704 rows x 8 columns]

In [ ]:
ticker = Ticker("SBER")

data = ticker.candles(
    start=dataBegin,
    end="today",
    period=1
)
begin = data["begin"].min()
print()

KeyError: 'tradedate'

In [7]:
data

,open,close,high,low,value,volume,begin,end
0,79.90,79.55,79.98,79.39,171268785.2,2151550,2011-12-15 10:00:00,2011-12-15 10:00:59
1,79.55,79.77,79.78,79.52,146627628.0,1841010,2011-12-15 10:01:00,2011-12-15 10:01:59
2,79.77,79.80,79.87,79.70,46946357.9,588320,2011-12-15 10:02:00,2011-12-15 10:02:59
3,79.80,79.82,79.94,79.78,70831346.3,887260,2011-12-15 10:03:00,2011-12-15 10:03:59
4,79.82,79.88,79.90,79.80,14813609.9,185520,2011-12-15 10:04:00,2011-12-15 10:04:59
...,...,...,...,...,...,...,...,...
9995,85.29,85.19,85.29,85.16,34168279.6,400930,2012-01-12 10:21:00,2012-01-12 10:21:59
9996,85.20,85.25,85.26,85.15,26172339.1,307200,2012-01-12 10:22:00,2012-01-12 10:22:59
9997,85.25,85.23,85.27,85.22,6103386.8,71590,2012-01-12 10:23:00,2012-01-12 10:23:59
9998,85.23,85.27,85.27,85.23,32646950.2,382900,2012-01-12 10:24:00,2012-01-12 10:24:59
9999,85.27,85.27,85.33,85.27,14229576.2,166850,2012-01-12 10:25:00,2012-01-12 10:25:59

In [ ]:
begin = data["begin"].min()
begin = data["begin"].max().split(' ')[0]
begin

'2012-01-12'